### ISSUE TITLE
transaction.name no longer has multi-field mapping

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#985]
I ran apm-integration-testing today and noticed that basically everything is failing. Tracked it down to the "transaction.name.keyword" match which is failing because there is no such field. It's just transaction.name with keyword type.

https://apm-ci.elastic.co/job/elastic+apm-integration-testing+master+push/51/consoleFull

**Comment by axw** [comment]
IIUC, the index template should define that mapping, but it's not:

> 2018-06-01T09:28:11.845Z        DEBUG   [elasticsearch] elasticsearch/client.go:708     PUT http://elasticsearch:9200/_template/apm-7.0.0-alpha1  map[index_patterns:[apm-7.0.0-alpha1-*] mappings:{"doc":{"_meta":{"version":"7.0.0-alpha1"},"date_detection":false,"dynamic_templates":[{"strings_as_keyword":{"mapping":{"ignore_above":1024,"type":"keyword"},"match_mapping_type":"string"}}],"properties":{}}} order:1 settings:{"index":{"codec":"best_compression","mapping":{"total_fields":{"limit":10000}},"number_of_routing_shards":30,"number_of_shards":1,"refresh_interval":"5s"}}]

**Comment by axw** [comment]
Yep, on master "apm-server export template" doesn't include any of our fields. Bisected to a64eb29cce2e0c84074d169534083761f5d3795c.

**Comment by beniwohli** [comment]
awesome catch @axw! Hopefully this is also going to fix elastic/apm-integration-testing/issues/73
