### PR TITLE
update beats' deps too

### LINKED ISSUE #450: deps of deps not updating
#447 was failing because beats' dependency golang.org/x/crypto is being updated, golang.org/x/crypto/'s dependency on golang.org/x/sys/unix is not.

steps to reproduce:

```
# in apm-server
## fda7d0a15 is current apm-server master HEAD
## e19f2a6f6 is current beats master HEAD
git checkout fda7d0a15fea6d86e33a55dbc3591e4956925451:
govendor fetch github.com/elastic/beats/...@e19f2a6f639496d94eaee8cb06ec2c600766563f
```

updates:
```
vendor/github.com/elastic/beats/...
vendor/go.uber.org/
vendor/golang.org/x/crypto/
vendor/golang.org/x/sys/windows/registry/
vendor/golang.org/x/sys/windows/svc/eventlog/
```

and fails:
```
$ go test .
# github.com/elastic/apm-server/vendor/golang.org/x/crypto/ssh/terminal
vendor/golang.org/x/crypto/ssh/terminal/util.go:30:12: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:38:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:54:12: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:64:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:75:9: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:80:13: undefined: unix.IoctlGetWinsize
vendor/golang.org/x/crypto/ssh/terminal/util.go:98:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:107:12: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:112:3: undefined: unix.IoctlSetTermios
FAIL	github.com/elastic/apm-server [build failed]
```

those were introduced in a newer golang.org/x/sys than apm has vendored.  Updating that using the same **beats** commit fixes it:

```
## e19f2a6f6 is current beats master HEAD
govendor fetch golang.org/x/sys/unix@e19f2a6f639496d94eaee8cb06ec2c600766563f
$ go test .
ok  	github.com/elastic/apm-server	0.038s
```

### PR DESCRIPTION
**Pull request by graphaelli**
fixes #450.  Adds 45 seconds to `make update-beats` on my machine.

includes 2 bug fixes too introduced in #449:
* `#!/usr/bin/env bash -ex` is not portable apparently, switched to `env bash` and a `set -ex`
* `BEATS_VERSION` specification only worked for branches

### CODE REVIEW

File: script/update_beats.sh [hunk 1]
```diff
@@ -1,17 +1,24 @@
...
+DIRNAME=$(dirname "$0")
+BASEDIR=${DIRNAME}/../_beats
 mkdir -p $BASEDIR
-cd $BASEDIR
+pushd $BASEDIR
 
 # Check out beats repo for updating
 GIT_CLONE=repo
-trap "{ rm -rf ${GIT_CLONE}; }" EXIT
+trap "{ rm -rf ${BASEDIR}/${GIT_CLONE}; }" EXIT
```
Comment (graphaelli) [inline script/update_beats.sh]: just noticed this doesn't work if exit happens before the `popd`.

**Comment by graphaelli** [comment]
Performing the last beats update makes quite a different update: https://github.com/elastic/apm-server/compare/02314b6dc844b4e18a2f3c450924ef58f6709e2a...graphaelli:test-beats-2924e6e-update

generated with:
```git checkout --branch test-beats-2924e6e-update 02314b6dc844b4e18a2f3c450924ef58f6709e2a^
# pull in update-beats changes from https://github.com/elastic/apm-server/pull/449 + this PR
git cherry-pick -n e8b222f6ec370fe004e053166400cce2b03e2923 b4fa8a1cfa8d7b8c710be2baa21938587f23b497
export BEATS_VERSION=2924e6ecab1ef842eb6f10e37b7f74980523c5b2
make update-beats
# rebase two cherry-picks out for smaller diff
```

File: script/update_govendor_deps.py [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        for pkg in sorted(packages):
+            print(pkg)
+        return
+
+    # much faster to call govendor once and minimize the git reset & status calls it makes
+    update = ['{pkg}@{revision}'.format(pkg=pkg, revision=args.revision) for pkg in packages]
+    cmd = ['govendor', 'fetch'] + update
+    if args.verbose:
+        print(cmd)
+    subprocess.check_call(cmd)
```
Comment (graphaelli) [inline script/update_govendor_deps.py]: change to `' '.join(cmd)`

File: script/update_beats.sh (hunk 1 above)
Comment (simitt) [reply script/update_beats.sh]: I've never used `pushd` and `popd` before but from reading what it does, do you even need to use `${BASEDIR}` here again or would it be enough to `rm -rf ${GIT_CLONE}`?

Comment (graphaelli) [reply script/update_beats.sh]: I experimented with killing the script in a bunch of places to confirm that the `rm` is executed relative to the working directory pushd leaves the script in before exiting.  One gross fix is to popd and ignore its error within the trap, that might have to do for now.

Comment (graphaelli) [reply script/update_beats.sh]: Implemented that in https://github.com/elastic/apm-server/pull/459/commits/5869b6524baeacaaad2858538e7b5b6394e6aa3d
